import { test, expect } from '@playwright/test';

test('CarScanner_UI_Tests', async ({ page }) => {
  await page.goto('file:///C:/Users/sh995514/Downloads/Varex%20Cargo%20UI%2006152026%202.html');
  await page.getByRole('button', { name: 'operator' }).click();
  await page.locator('#themeToggleItem').click();
  await page.getByRole('button', { name: 'operator' }).click();
  await page.getByText('Menu on right').click();
  await page.getByRole('button', { name: 'operator' }).click();
  await page.getByText('Menu on right').click();
  await page.getByRole('button', { name: 'operator' }).click();
  await page.getByText('Menu on left').click();
  await page.getByRole('button', { name: 'Inspection', exact: true }).click();
  await page.getByRole('button', { name: 'Inspection', exact: true }).click();
  await page.getByRole('button', { name: 'Live view' }).click();
  await page.getByRole('button', { name: 'Dual energy' }).click();
  await page.getByRole('button', { name: '3D view' }).click();
  await page.getByRole('button', { name: 'Analytics' }).click();
  await page.getByRole('button', { name: 'Recent scans' }).click();
  await page.getByRole('button', { name: 'Flagged items' }).click();
  await page.getByRole('button', { name: 'Search log' }).click();
  await page.getByRole('button', { name: 'Throughput' }).click();
  await page.getByRole('button', { name: 'Alarm statistics' }).click();
  await page.getByRole('button', { name: 'Operator stats' }).click();
  await page.getByRole('button', { name: 'Threat library' }).click();
  await page.getByRole('button', { name: 'Weapons' }).click();
  await page.getByRole('button', { name: 'Explosives' }).click();
  await page.getByRole('button', { name: 'Prohibited items' }).click();
  await page.getByRole('button', { name: 'System' }).click();
  await page.getByRole('button', { name: 'X-ray source' }).click();
  await page.getByRole('button', { name: 'Detectors' }).click();
  await page.getByRole('button', { name: 'Belt' }).click();
  await page.getByRole('button', { name: 'Users' }).click();
  await page.getByRole('button', { name: 'Network' }).click();
  await page.getByRole('button', { name: 'Diagnostics' }).click();
  await page.getByRole('button', { name: 'About', exact: true }).click();
  await page.getByRole('button', { name: 'Zoom in' }).click();
  await page.getByRole('button', { name: 'Zoom out' }).click();
  await page.getByRole('button', { name: 'Zoom out' }).click();
  await page.getByRole('button', { name: 'Toggle organic material color' }).click();
  await page.getByRole('button', { name: 'Toggle dense material' }).click();
  await page.getByRole('button', { name: 'Toggle high density highlight' }).click();
  await page.getByRole('button', { name: 'Invert image colors' }).click();
  await page.getByRole('button', { name: 'Toggle edge enhancement' }).click();
  await page.getByRole('button', { name: 'Apply log preset 1' }).click();
  await page.getByRole('button', { name: 'Apply log preset 2' }).click();
  await page.getByRole('button', { name: 'Apply log preset 2' }).click();
  await page.getByRole('button', { name: 'Apply log preset 4' }).click();
  await page.getByRole('button', { name: 'Reset view and image' }).click();
  await page.getByRole('button', { name: 'Clear bag and send onward' }).click();
  await page.getByRole('button', { name: 'Escalate for secondary' }).click();
  await page.getByRole('button', { name: 'Previous scan' }).click();
  await page.getByRole('button', { name: 'Next scan' }).click();
  await page.getByText('x-ray on').click();
  await page.getByText('scanning').click();
  await page.getByText('e-stop').click();
  await page.getByText('system health').click();
});